# Generated by Django 3.1.1 on 2020-09-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_mangement_app', '0005_contactstaff_contactstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactstaff',
            name='read_status',
        ),
        migrations.RemoveField(
            model_name='contactstudent',
            name='read_status',
        ),
    ]
