# Generated by Django 3.1.1 on 2020-09-24 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_mangement_app', '0006_auto_20200924_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactstaff',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_mangement_app.staffs'),
        ),
    ]
