# Generated by Django 3.1.1 on 2020-09-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_mangement_app', '0007_auto_20200924_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='subject_assignment_marks',
            new_name='subject_assignment2_marks',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject_assignment1_marks',
            field=models.FloatField(default=0),
        ),
    ]
