# Generated by Django 3.1.1 on 2020-10-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_mangement_app', '0008_auto_20200924_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='attendance_program_pic')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_mangement_app.courses')),
            ],
        ),
    ]
