# Generated by Django 3.1.1 on 2020-10-03 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_mangement_app', '0010_studentinfo_studentinforeport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='studentinforeport',
            name='staff_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_mangement_app.staffs'),
            preserve_default=False,
        ),
    ]
