# Generated by Django 3.1.1 on 2020-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_mangement_app', '0011_auto_20201003_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='info',
        ),
        migrations.AddField(
            model_name='studentinforeport',
            name='info',
            field=models.TextField(default=1, max_length=4000),
            preserve_default=False,
        ),
    ]
