# Generated by Django 3.1.1 on 2020-10-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_mangement_app', '0013_studentinfo_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinforeport',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
