# Generated by Django 3.1.1 on 2020-10-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_mangement_app', '0014_auto_20201009_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
